spring:
  datasource:
    url: jdbc:mysql://database:3306/userdb
    username: user
    password: userpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none