spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: user
    password: userpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 15000
    maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
